In [1]:
import numpy as np
import cv2

In [2]:
def compute_vector_length(vector):
    len_of_vector = np.linalg.norm(vector)
    return len_of_vector

def compute_dot_product(vector1, vector2):
    return np.dot(vector1, vector2)

def matrix_multi_vector(matrix, vector):
    return np.dot(matrix, vector)

def matrix_multi_matrix(matrix1, matrix2):
    return np.dot(matrix1, matrix2)

def inverse_matrix(matrix):
    return np.linalg.inv(matrix)

def compute_eigenvalues_eigenvectors(matrix):
    return np.linalg.eig(matrix)

def compute_cosine(v1, v2):
    return (np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2)))


In [3]:
vector = np.array([-2, 4, 9, 21])
result = compute_vector_length([vector])
print(round(result, 2))

v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1, 0])
result = compute_dot_product(v1, v2)
print(round(result, 2))

x = np.array([[1, 2], [3, 4]])
k = np.array([1, 2])
print("result \n", x.dot(k))

x = np.array([[-1, 2], [3, -4]])
k = np.array([1, 2])
print("result \n", x @ k)

m = np.array([[-1, 1, 1], [0, -4, 9]])
v = np.array([0, 2, 1])
result = matrix_multi_vector(m, v)
print(result)

m1 = np.array([[0, 1, 2], [2, -3, 1]])
m2 = np.array([[1, -3], [6, 1], [0, -1]])
result = matrix_multi_matrix(m1, m2)
print(result)

m1 = np.eye(3)
m2 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
result = m1 @ m2
print(result)

m1 = np.eye(2)
m1 = np.reshape(m1, (-1, 4))[0]
m2 = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1 @ m2
print(result)

m1 = np.array([[1, 2], [3, 4]])
m1 = np.reshape(m1, (-1, 4), "F")[0]
m2 = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1 @ m2
print(result)

m1 = np.array([[-2, 6], [8, -4]])
result = inverse_matrix(m1)
print(result)

matrix = np.array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
result = compute_cosine(x, y)
print(round(result, 3))

"""
1. D
2. B
3. A
4. B
5. A
6. C
7. A
8. D
9. B
10. A
11. A
12. C
"""

23.28
4
result 
 [ 5 11]
result 
 [ 3 -5]
[3 1]
[[  6  -1]
 [-16 -10]]
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
[5. 5. 5. 5.]
[29 29 29 29]
[[0.1  0.15]
 [0.2  0.05]]
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
0.577


'\n1. D\n2. B\n3. A\n4. B\n5. A\n6. C\n7. A\n8. D\n9. B\n10. A\n11. A\n12. C\n'

In [4]:
bg1_image = cv2.imread('GreenBackground.png', 1)
bg1_image = cv2.resize(bg1_image, (678, 381))

ob_image = cv2.imread('Object.png', 1)
ob_image = cv2.resize(ob_image, (678, 381))

bg2_image = cv2.imread('NewBackground.jpg', 1)
bg2_image = cv2.resize(bg2_image, (678, 381))


In [ ]:
def compute_difference(bg_img, input_img):
    difference_single_channel = cv2.absdiff(bg_img, input_img)
    difference_single_channel = np.sum(difference_single_channel, axis=2)/3.0
    difference_single_channel = difference_single_channel.astype('uint8')
    return difference_single_channel

def computeBinaryMask(difference_single_channel):
    difference_binary = np.where(difference_single_channel >= 15, 255, 0).astype(np.uint8)
    difference_binary = np.stack((difference_binary,)*3, axis=-1)
    return difference_binary

def replaceBackground(bg1_image, bg2_image, ob_image):
    difference_single_channel = compute_difference(bg1_image, ob_image)
    binary_mask = computeBinaryMask(difference_single_channel)
    output = np.where(binary_mask==255, ob_image, bg2_image)
    return output

output = replaceBackground(bg1_image, bg2_image, ob_image)
cv2.imshow('Image', output)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
